version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - docker build -t $IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed
      - docker push $IMAGE_REPO_NAME
artifacts:
  files:
    - target/bootcamp.jar